name = "SensitivityRankCondition"
uuid = "713b81e2-6747-41cf-8c92-2c171e94ab1f"
authors = ["JinraeKim <kjl950403@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
ComponentArrays = "0.13"
ForwardDiff = "0.10"
OrdinaryDiffEq = "6.49"
julia = "1"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyCall"]
